[project]
name = "transportsimple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
]

[dependency-groups]
dev = [
    "django-stubs>=5.1.3",
    "ipdb>=0.13.13",
]
